### PR TITLE
import defaul enUS from date-fns/locale not from esm version

### PR DESCRIPTION
**Pull request by Julian-B90**
fix issue #10

### CODE REVIEW

**Comment by Julian-B90** [comment]
Hey @sapozhnikovay thanks for merge. Can you update the Branch with the Version 12 with this fix?

**Comment by sapozhnikovay** [comment]
@Julian-B90 I'll try to do this today.

**Comment by sapozhnikovay** [comment]
The main reason for the merge delay btw was the need to ensure that there is no regression for the issue #4 
Date-fns authors have fixed the wrong ES Modules export in April with version 2.20.3

**Comment by sapozhnikovay** [comment]
Updated version_12 branch. Released version 12.0.0-beta.1 with this changes. Under the same tag `ivy` in npm.

**Comment by Julian-B90** [comment]
Nice @sapozhnikovay thank you

**Pull request merged**
